// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCktmKi52TwkRFzMl_8JIuS0RJGStfW7Ck',
    appId: '1:687845532589:web:93a2ba9f2a25c96f203724',
    messagingSenderId: '687845532589',
    projectId: 'inventory-management-app-82c06',
    authDomain: 'inventory-management-app-82c06.firebaseapp.com',
    storageBucket: 'inventory-management-app-82c06.firebasestorage.app',
    measurementId: 'G-EY656DV3C2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgoKK0aOLR58nqsxj9cz32D71umqDOoEc',
    appId: '1:687845532589:android:2a2e1a239021b2db203724',
    messagingSenderId: '687845532589',
    projectId: 'inventory-management-app-82c06',
    storageBucket: 'inventory-management-app-82c06.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBneQCsZrBrrk1E6zfJybPL9BMzSgCMdL8',
    appId: '1:687845532589:ios:2f1434957316e1c6203724',
    messagingSenderId: '687845532589',
    projectId: 'inventory-management-app-82c06',
    storageBucket: 'inventory-management-app-82c06.firebasestorage.app',
    iosBundleId: 'com.example.inventoryManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBneQCsZrBrrk1E6zfJybPL9BMzSgCMdL8',
    appId: '1:687845532589:ios:2f1434957316e1c6203724',
    messagingSenderId: '687845532589',
    projectId: 'inventory-management-app-82c06',
    storageBucket: 'inventory-management-app-82c06.firebasestorage.app',
    iosBundleId: 'com.example.inventoryManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCktmKi52TwkRFzMl_8JIuS0RJGStfW7Ck',
    appId: '1:687845532589:web:59da430adf0859e6203724',
    messagingSenderId: '687845532589',
    projectId: 'inventory-management-app-82c06',
    authDomain: 'inventory-management-app-82c06.firebaseapp.com',
    storageBucket: 'inventory-management-app-82c06.firebasestorage.app',
    measurementId: 'G-DHCDG6P4QT',
  );
}
